### ISSUE TITLE
movePlayerTo does not always work

### ISSUE THREAD

**Issue by alien35** [decentraland/ui#136]
the movePlayerTo function from @decentraland/RestrictedActions does not always work.
To reproduce:
1. Create a wall or something at the edge of your land
2. Add a movePlayerTo function to said wall
1. Stand outside of the perimeters of your land
2. inside the game, click "Move player" or whatever is rendered on the screen

If you are outside of the perimeters of your land, you may see the words "Move player" but it will not actually execute.

Screenshot:
<img width="1080" alt="Screen Shot 2022-02-17 at 9 42 25 PM" src="https://user-images.githubusercontent.com/19285492/154607551-5485abe1-d282-449b-905f-687800fb8a2d.png">

**Comment by nicosantangelo** [comment]
Hey there! I think you probably wanted to open this issue on the [Decentraland Client](https://github.com/decentraland/unity-renderer) as this repo it's just for [ui related stuff of our dapps](https://ui.decentraland.org/)

I'll close it but feel free to let me know if I miss-interpreted the issue
