### ISSUE TITLE
Style bugs

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/ui#15]
## Address Field

1)
Not adding a label makes the blockie fall

![image](https://user-images.githubusercontent.com/692077/44364245-c3304300-a4c6-11e8-88aa-0b001a8141a5.png)
![image 1](https://user-images.githubusercontent.com/692077/44364247-c4617000-a4c6-11e8-9e18-e98f6ac736a9.png)

2) _Maybe related to all fields_

Mobile styles for really small phones leak horizontally to the right:

![image](https://user-images.githubusercontent.com/692077/44364527-8a449e00-a4c7-11e8-98dd-a51bd5fe9435.png)

because of this style:

![image](https://user-images.githubusercontent.com/692077/44364575-a6e0d600-a4c7-11e8-9016-4925b4fffc3d.png)

## Mana inline

This
![image](https://user-images.githubusercontent.com/692077/44364416-3934aa00-a4c7-11e8-9c12-ed1efd7b0ded.png)

yields
![image](https://user-images.githubusercontent.com/692077/44364422-3fc32180-a4c7-11e8-9c1c-5eea2226a072.png)

## Navbar blockie

The navbar blockie has a `cursor:pointer` even if it doesn't have a handler `onClick` (check agora)

## Button secondary

Using a button secondary on a Segment in a dark theme lacks styling:

![image](https://user-images.githubusercontent.com/692077/44420866-69d81a80-a57f-11e8-8b2d-e347bd8358f8.png)

**Comment by cazala** [comment]
All these are fixed already on v2
